"""Composition table

Revision ID: 496667941899
Revises: 42e2f3150b5a
Create Date: 2021-11-05 16:34:33.592949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496667941899'
down_revision = '42e2f3150b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_type', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compositions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compositions_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compositions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compositions_timestamp'))

    op.drop_table('compositions')
    # ### end Alembic commands ###
