"""description html

Revision ID: 02e7efb289d2
Revises: 496667941899
Create Date: 2021-11-09 16:20:09.485843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e7efb289d2'
down_revision = '496667941899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compositions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compositions', schema=None) as batch_op:
        batch_op.drop_column('description_html')

    # ### end Alembic commands ###
